# Usar una imagen base de Node.js
FROM node:latest

# Establecer el directorio de trabajo
WORKDIR /usr/app/

# Copiar solo los archivos necesarios
COPY ./package.json ./package-lock.json ./
COPY ./gulpfile.js ./
COPY ./src ./src/

RUN mkdir -p ./public/build

# Instalar dependencias
RUN npm install